apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: platform.worker
  namespace: vote
spec:
  tier: platform
  order: 120
  selector: app == 'worker'
  types:
  - Egress
  egress:
  - action: Allow
    protocol: TCP
    destination:
      selector: app == 'redis'
      ports:
      - 6379
  - action: Allow
    protocol: TCP
    destination:
      selector: app == 'db'
      ports:
      - 5432 