apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: platform.result
  namespace: vote
spec:
  tier: platform
  order: 130
  selector: app == 'result'
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
    protocol: TCP
    source: {}
    destination:
      ports:
      - 80
  egress:
  - action: Allow
    protocol: TCP
    destination:
      selector: app == 'db'
      ports:
      - 5432