apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: platform.vote
  namespace: vote
spec:
  tier: platform
  order: 140
  selector: app == 'vote'
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
    protocol: TCP
    source: {}
    destination:
      ports:
      - 80
  egress:
  - action: Allow
    protocol: TCP
    destination:
      selector: app == 'redis'
      ports:
      - 6379